// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");
const webdriver = require("selenium-webdriver");

describe("charityTest", function () {
  require("chromedriver");
  const webdriver = require("selenium-webdriver");
  let driver = new webdriver.Builder().forBrowser("chrome").build();
  let vars;
  beforeEach(async function () {
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("charityTest", async function () {
    driver.get("http://localhost:3000/").then(function () {
      return driver.then(function () {
        return driver
          .findElement(By.linkText("Charities"))
          .click()
          .then(function () {
            driver.executeScript("window.scrollTo(0,0)").then(function () {
              driver
                .findElement(
                  By.css(".charity-card:nth-child(1) .card-btn-left")
                )
                .click()
                .then(function () {
                  driver
                    .executeScript("window.scrollTo(0,0)")
                    .then(function () {
                      driver
                        .manage()
                        .window()
                        .setRect({ width: 725, height: 796 });
                      driver.sleep(20000);
                    });
                });
            });
          });
      });
    });
  });
});
