// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");
const webdriver = require("selenium-webdriver");
const WebDriverWait = require("selenium-webdriver");
import React from "react";

describe("localLogin", function () {
  require("chromedriver");
  const webdriver = require("selenium-webdriver");
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new webdriver.Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("localLogin", async function () {
    driver.get("http://localhost:3000/").then(function () {
      return driver
        .wait(until.elementLocated(By.css(".sign-in-btn")), 20000)
        .then(function () {
          return driver
            .findElement(By.linkText("Login"))
            .click()
            .then(function () {
              driver
                .findElement(By.name("email"))
                .click()
                .then(function () {
                  driver
                    .findElement(By.name("email"))
                    .sendKeys("saniya.ibraimova@gmail.com")
                    .then(function () {
                      driver
                        .findElement(By.name("password"))
                        .click()
                        .then(function () {
                          driver
                            .findElement(By.name("password"))
                            .sendKeys("unicorn")
                            .then(function () {
                              driver
                                .findElement(By.css(".sign-in-btn"))
                                .click()
                                .then(function () {
                                  driver
                                    .manage()
                                    .window()
                                    .setRect({ width: 1323, height: 797 });
                                  driver.sleep(20000).then(function () {
                                    return driver
                                      .findElement(By.css(".sign-in-btn"))
                                      .click();
                                  });
                                });
                            });
                        });
                    });
                });
            });
        });
    });
  });
});
