// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");
const webdriver = require("selenium-webdriver");

describe("signUp", function () {
  require("chromedriver");
  const webdriver = require("selenium-webdriver");
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new webdriver.Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("signUp", async function () {
    driver.get("http://localhost:3000/").then(function () {
      return driver
        .wait(until.elementLocated(By.css(".sign-in-btn")), 20000)
        .then(function () {
          return driver
            .findElement(By.linkText("Login"))
            .click()
            .then(function () {
              driver
                .findElement(By.linkText("Sign up"))
                .click()
                .then(function () {
                  driver
                    .findElement(
                      By.css(".email-field > .login-txt:nth-child(3)")
                    )
                    .click()
                    .then(function () {
                      driver
                        .findElement(
                          By.css(".email-field > .login-txt:nth-child(3)")
                        )
                        .sendKeys("saniya.ibraimova@gmail.com")
                        .then(function () {
                          driver
                            .findElement(
                              By.css(
                                "div:nth-child(4) > .login-txt:nth-child(3)"
                              )
                            )
                            .click()
                            .then(function () {
                              driver
                                .findElement(
                                  By.css(
                                    "div:nth-child(4) > .login-txt:nth-child(3)"
                                  )
                                )
                                .sendKeys("unicorn")
                                .then(function () {
                                  driver
                                    .findElement(By.css("div:nth-child(5)"))
                                    .click()
                                    .then(function () {
                                      driver
                                        .findElement(By.css(".checkbox"))
                                        .click()
                                        .then(function () {
                                          driver
                                            .findElement(By.css(".sign-in-btn"))
                                            .click()
                                            .then(function () {
                                              driver
                                                .findElement(
                                                  By.css(
                                                    ".form-input:nth-child(1) input"
                                                  )
                                                )
                                                .click()
                                                .then(function () {
                                                  driver
                                                    .findElement(
                                                      By.css(
                                                        ".form-input:nth-child(1) input"
                                                      )
                                                    )
                                                    .sendKeys("Saniya")
                                                    .then(function () {
                                                      driver
                                                        .findElement(
                                                          By.css(
                                                            ".form-input:nth-child(2) input"
                                                          )
                                                        )
                                                        .sendKeys("Baghirova")
                                                        .then(function () {
                                                          driver
                                                            .findElement(
                                                              By.css(
                                                                ".form-input:nth-child(4) input"
                                                              )
                                                            )
                                                            .sendKeys(
                                                              "+4746577530"
                                                            )
                                                            .then(function () {
                                                              driver
                                                                .findElement(
                                                                  By.css(
                                                                    ".input-form"
                                                                  )
                                                                )
                                                                .click()
                                                                .then(
                                                                  function () {
                                                                    driver
                                                                      .findElement(
                                                                        By.css(
                                                                          ".form-input:nth-child(4) input"
                                                                        )
                                                                      )
                                                                      .sendKeys(
                                                                        "77788999"
                                                                      )
                                                                      .then(
                                                                        function () {
                                                                          driver
                                                                            .findElement(
                                                                              By.css(
                                                                                ".input-field"
                                                                              )
                                                                            )
                                                                            .click()
                                                                            .then(
                                                                              function () {
                                                                                driver
                                                                                  .findElement(
                                                                                    By.css(
                                                                                      ".form-input:nth-child(7) input"
                                                                                    )
                                                                                  )
                                                                                  .click()
                                                                                  .then(
                                                                                    function () {
                                                                                      driver
                                                                                        .findElement(
                                                                                          By.css(
                                                                                            ".form-input:nth-child(7) input"
                                                                                          )
                                                                                        )
                                                                                        .sendKeys(
                                                                                          "787890906767"
                                                                                        )
                                                                                        .then(
                                                                                          function () {
                                                                                            driver
                                                                                              .findElement(
                                                                                                By.css(
                                                                                                  ".form-input:nth-child(8) input"
                                                                                                )
                                                                                              )
                                                                                              .click()
                                                                                              .then(
                                                                                                function () {
                                                                                                  driver
                                                                                                    .findElement(
                                                                                                      By.css(
                                                                                                        ".form-input:nth-child(8) input"
                                                                                                      )
                                                                                                    )
                                                                                                    .sendKeys(
                                                                                                      "Test company"
                                                                                                    )
                                                                                                    .then(
                                                                                                      function () {
                                                                                                        driver
                                                                                                          .findElement(
                                                                                                            By.css(
                                                                                                              ".form-input:nth-child(9) input"
                                                                                                            )
                                                                                                          )
                                                                                                          .click()
                                                                                                          .then(
                                                                                                            function () {
                                                                                                              driver
                                                                                                                .findElement(
                                                                                                                  By.css(
                                                                                                                    ".form-input:nth-child(9) input"
                                                                                                                  )
                                                                                                                )
                                                                                                                .sendKeys(
                                                                                                                  "test title"
                                                                                                                )
                                                                                                                .then(
                                                                                                                  function () {
                                                                                                                    driver
                                                                                                                      .findElement(
                                                                                                                        By.css(
                                                                                                                          ".sign-in-btn"
                                                                                                                        )
                                                                                                                      )
                                                                                                                      .click()

                                                                                                                      .then(
                                                                                                                        function () {
                                                                                                                          driver
                                                                                                                            .manage()
                                                                                                                            .window()
                                                                                                                            .setRect(
                                                                                                                              {
                                                                                                                                width: 598,
                                                                                                                                height: 797,
                                                                                                                              }
                                                                                                                            );
                                                                                                                          driver.sleep(
                                                                                                                            20000
                                                                                                                          );
                                                                                                                        }
                                                                                                                      );
                                                                                                                  }
                                                                                                                );
                                                                                                            }
                                                                                                          );
                                                                                                      }
                                                                                                    );
                                                                                                }
                                                                                              );
                                                                                          }
                                                                                        );
                                                                                    }
                                                                                  );
                                                                              }
                                                                            );
                                                                        }
                                                                      );
                                                                  }
                                                                );
                                                            });
                                                        });
                                                    });
                                                });
                                            });
                                        });
                                    });
                                });
                            });
                        });
                    });
                });
            });
        });
    });
  });
});
